name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
          destination_dir: ${{ github.ref_name }}  # dev or prod folder
          publish_branch: gh-pages 
          keep_files: true 
          
      - name: Set Pages URL
        run: |
          echo "Deployed to https://mutur1.github.io/${{ github.repository }}/${{ github.ref_name }}/"